
TUNING.STRING_SHADOW_DECAYED = "Bye my shadow friend..."
TUNING.STRING_SHADOW_DECAYS = "My Shadow friend has become paler, he needs nightmarefuel..."

GLOBAL.STRINGS.NAMES.JOURNALPAGE = "Codex Umbra Page"
GLOBAL.STRINGS.RECIPE_DESC.JOURNALPAGE = "Used to bind shadows to a certain location"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.JOURNALPAGE = "The torn out pages seem to grow back on the book rather quickly."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOWWAXWELL = "A Shadowminion"

GLOBAL.STRINGS.RECIPE_DESC.SHADOWLUMBER_BUILDER = "Does every work" 
GLOBAL.STRINGS.NAMES.SHADOWLUMBER_BUILDER = "Shadow Worker"

GLOBAL.STRINGS.ACTIONS.BM_SHADOWTOGGLE = { STOPWORKING = GLOBAL.STRINGS.ACTIONS.TURNOFF.GENERIC, STARTWORKING = GLOBAL.STRINGS.ACTIONS.TURNON.GENERIC or GLOBAL.STRINGS.ACTIONS.TURNON }
GLOBAL.STRINGS.ACTIONS.BM_SHADOWCALL = "Call Shadows"



