name = "Evolving Maxwell Shadows"
description = "Shadows use weapons/armor/tools like normal players and can be upgraded by giving nightmarefuel to them. \nWorker is able to pick and dig saplings/grass/bushes if you want and can also focus on tall trees to chop.\nYou can customize nearly everything in modsettings.\nNo original game scripts overwritten, so much more compatible to game updates!."
author = "Serp,Weexer,PI_RATE,rezecib"

version = "1.000"

forumthread = ""

api_version = 10

dst_compatible = true
dont_starve_compatible = false
reign_of_giants_compatible = false

all_clients_require_mod = true
clients_only_mod = false

icon = "modicon.tex"
icon_atlas = "modicon.xml"

server_filter_tags = {"maxwell_shadows","evolving_maxwell_shadows"}


configuration_options =
{
	{
        name = "maxwell_health",
        label = "Maxwell Max Health",
        hover = "Set maximum health for Maxwell",
        options =
        {
            {description = "50", data = 50, hover = "That's not funny at all"},
            {description = "Vanilla (75)", data = false, hover = "Vanilla Setting / Recommended"},
            {description = "100", data = 100, hover = ""},
            {description = "125", data = 125, hover = "A little more"},
            {description = "150", data = 150, hover = "Wilson's health"},
            {description = "175", data = 175, hover = "Very tanky build"},
            {description = "200", data = 200, hover = "That's a lot of health"},
        },
        default = false,
	},
	{
        name = "maxwell_sanity",
        label = "Maxwell Max Sanity",
        hover = "Set maximum sanity for Maxwell",
        options =
        {
			{description = "100", data = 100},
            {description = "150", data = 150},
            {description = "Vanilla (200)", data = false, hover = "Vanilla Setting / Recommended"},
            {description = "250", data = 250},
            {description = "300", data = 300},
        },
        default = false,
	},
	{
        name = "maxwell_sanity_regen",
        label = "Maxwell Sanity Regeneration",
        hover = "Set how fast sanity regenerate for Maxwell",
        options =
        {
            {description = "None", data = 3},
            {description = "Tiny", data = 4},
            {description = "Small", data = 5},
            {description = "Medium", data = 6},
            {description = "MediumLarge", data = 7},
            {description = "Vanilla (Large)", data = 8, hover = "Vanilla Setting - Recommended"},
			{description = "Huge", data = 9},
			{description = "Superhuge", data = 10, hover = "Same as in Don't Starve"},
        },
		default = 8,
	},
    {
        name = "nightmarefuel_start",
        label = "Extra Nightmarefuel on Start",
        hover = "Set how many extra nightmarefuels Maxwell will have on start",
        options =
        {
            {description = "-6", data = -6, hover = "0 in default game"},
            {description = "-5", data = -5, hover = "1 in default game"},
            {description = "-4", data = -4, hover = "2 in default game"},
            {description = "-3", data = -3, hover = "3 in default game"},
            {description = "-2", data = -2, hover = "4 in default game"},
            {description = "-1", data = -1, hover = "5 in default game"},
            {description = "+0", data = 0, hover = "6 Vanilla Setting / Recommended"},
            {description = "+1", data = 1, hover = "7 in default game"},
            {description = "+2", data = 2, hover = "8 in default game"},
            {description = "+3", data = 3, hover = "9 in default game"},
            {description = "+4", data = 4, hover = "10 in default game"},
			{description = "+14", data = 14, hover = "20 in default game"},
            {description = "+34", data = 34, hover = "40 in default game"},
        },
        default = 0,
	},
    {
        name = "unlock_recipe",
        label = "Learnable Recipes?",
        hover = "Do you want to learn the shadow recipes, so you dont need the Codex Umbra anymore (after summoning them once)?",
        options =
        {
            {description = "Default", data = false, hover = "Vanilla Setting - you always need the book to cast shadows."},
            {description = "Learnable", data = true, hover = "You can learn the recipe after casting it once, no need to carry the book any longer"},
        },
        default = false,
	},
    {
        name = "null",
        label = "##### Shadow settings #####",
        hover = "",
        options =	{
						{description = "", data = 1, hover = ""},
					},
        default = 1,
	},
	{
        name = "shadow_worker_sanity",
        label = "Shadow Workers Penalty",
        hover = "Percentage max sanity cost of creating a Shadow Worker",
        options =
        {
            {description = "0%", data = 0},
            {description = "1%", data = 0.01},
            {description = "5%", data = 0.05},
            {description = "10%", data = 0.1},
            {description = "15%", data = 0.15},
            {description = "Vanilla (20%)", data = false, hover = "Vanilla Setting"},
            {description = "25%", data = 0.25},
            {description = "30%", data = 0.30},
            {description = "35%", data = 0.35},
            {description = "40%", data = 0.40},
        },
        default = false,
	},
    {
        name = "shadow_duelist_sanity",
        label = "Shadow Duelist Penalty",
        hover = "Percentage max sanity cost of creating a Shadow Duelist",
        options =
        {
            {description = "0%", data = 0},
            {description = "1%", data = 0.01},
            {description = "5%", data = 0.05},
            {description = "10%", data = 0.1},
            {description = "15%", data = 0.15},
            {description = "20%", data = 0.2},
            {description = "25%", data = 0.25},
            {description = "30%", data = 0.30, hover = "Recommended"},
            {description = "Vanilla (35%)", data = false, hover = "Vanilla Setting"},
            {description = "40%", data = 0.40},
        },
        default = 0.30,
	},
    {
        name = "shadow_sanity_drain",
        label = "Shadows Sanity Drain/Gain",
        hover = "Sanity drain/gain per active shadow per minute.",
        options = 
		{
            {description = "Small Tiny Gain", data = 1, hover="Gain"},
            {description = "Tiny Gain", data = 2, hover="Gain"},
            {description = "None", data = 3, hover="Vanilla Setting"},
            {description = "Tiny", data = 4, hover=""},
            {description = "Small Tiny", data = 5, hover="Recommended"},
            {description = "Small", data = 6, hover=""},
            {description = "Medium", data = 7, hover=""},
            {description = "Large", data = 8, hover=""},
            {description = "Huge", data = 9, hover=""},
            {description = "Super Huge", data = 10, hover=""},
        },
		default = 3,
	},
    {
        name = "maxwell_shadow_amount",
        label = "Max Amount Of Shadows",
        hover = "Set how many shadows can be summoned, keep sanity penalty in mind.  Because critters exist, you will get +1 !",
        options =
        {
            {description = "1", data = 1, hover = "Lonely wolf / hardcore option"},
            {description = "2", data = 2},
            {description = "3", data = 3},
            {description = "Vanilla (4)", data = false, hover = "Vanilla Setting / Recommended"},
            {description = "5", data = 5},
            {description = "6", data = 6},
            {description = "7", data = 7},
            {description = "8", data = 8},
            {description = "9", data = 9},
            {description = "10", data = 10},
            {description = "100", data = 100, hover = "Army of maxwells (You need good PC for that!)"},
        },
        default = false,
	},
    -- { -- is now automatically same speed as maxwell
        -- name = "shadow_maxwell_slowness",
        -- label = "Shadows Speed",
        -- hover = "Set how fast your friends run. With walking cane you are 1.25 times as fast, while shadows are not.",
        -- options =
        -- {
            -- {description = "*0.6", data = 0.6},
            -- {description = "*0.8", data = 0.8},
            -- {description = "*0.9", data = 0.9},
            -- {description = "Default", data = 1, hover = "Vanilla Setting"},
            -- {description = "*1.1", data = 1.1},
            -- {description = "*1.2", data = 1.2, hover = "Faster than Maxwell / Recommended"},
            -- {description = "*1.3", data = 1.3},
            -- {description = "*1.4", data = 1.4},
        -- },
        -- default = 1.2,
	-- },
    -- {
        -- name = "luck_chance",
        -- label = "1 Extra Fuel on Release",
        -- hover = "Set % chance for getting 1 extra nightmarefuel when shadow is released (not dying).",
        -- options =
        -- {
            -- {description = "0%", data = 0, hover = "Vanilla Setting"},
            -- {description = "10%", data = 0.1},
            -- {description = "20%", data = 0.2},
            -- {description = "30%", data = 0.3},
            -- {description = "40%", data = 0.4},
            -- {description = "50%", data = 0.5, hover = "Recommended"},
            -- {description = "60%", data = 0.6},
            -- {description = "70%", data = 0.7},
            -- {description = "80%", data = 0.8},
            -- {description = "90%", data = 0.9},
            -- {description = "100%", data = 1},
        -- },
        -- default = 0.5,
	-- },
    {
        name = "null",
        label = "### NEW Shadow System ###",
        hover = "Upgrade shadows by giving them nightmarefuel. 1 fuel = 1 level. Shadows will use tools/weapons just like players.",
        options =	{
						{description = "", data = 1, hover = ""},
					},
        default = 1,
	},
    {
        name = "level_enabled",
        label = "Level System?",
        hover = "Enable/Disable the level system. If disabled, your shadow will gain max level 1 (from 0). You can disable decay system in a below setting.",
        options =
        {
            {description = "Disabled", data = false, hover = "Shadows always stay (nearly) the same (health, attack, workeffectivness and so on)"},
            {description = "Enabled", data = true, hover = "Recommended - Shadows will become better the more nightmarefuel they consumed"},
        },
        default = true,
	},
    {
        name = "keep_upgrade_fuel",
        label = "Retrieve Upgrade-Fuel?",
        hover = "Retrieve Nightmarefuel used to upgrade Shadow on his release? (not on death)",
        options =
        {
            {description = "No", data = false, hover = "Recommended - Upgrade-Fuel is lost on his release"},
            {description = "Half", data = "half", hover = "Get half back"},
            {description = "Full", data = "full", hover = "Get all back"},
        },
        default = false,
	},
    {
        name = "upgrade_visuals",
        label = "Upgrade Visuals?",
        hover = "When upgrading with nightmarefuel, equipment can change colour to visualize the upgrade.",
        options =
        {
            {description = "Nothing", data = false, hover = ""},
            -- {description = "Size", data = "size", hover = "Gets as 4 times as big at max level 100"}, -- makes too mcuh problems
            {description = "Red", data = "red", hover = "Equipment gets more and more red"},
            {description = "Green", data = "green", hover = "Equipment gets more and more green"},
            {description = "Blue", data = "blue", hover = "Equipment gets more and more blue"},
            {description = "Yellow", data = "yellow", hover = "Equipment gets more and more yellow"},
            {description = "Purple", data = "purple", hover = "Equipment gets more and more purple"},
            {description = "Turquoise", data = "turquoise", hover = "Equipment gets more and more turquoise"},
        },
        default = "red",
	},
    {
        name = "shadow_decay_rate",
        label = "Shadows Decay",
        hover = "Shadows consume 1 nightmarefuel every x days. If none in their container, will consume level or will decay and disappear after 5 times without fuel.",
        options =
        {
            {description = "Off", data = 0, hover = "No decay, shadows last as long as you want"},
            {description = "0.1", data = 0.1, hover = "Every one-tenth day they need 1 fuel"},
            {description = "0.2", data = 0.2, hover = "Every one-fifth day they need 1 fuel"},
            {description = "0.33", data = 0.333, hover = "Every one-third day they need 1 fuel"},
            {description = "0.50", data = 0.500, hover = "Every half day they need 1 fuel"},
            {description = "0.66", data = 0.666, hover = "Every two-third day they need 1 fuel"},
            {description = "1", data = 1, hover = "Every day they need 1 fuel - Recommended"},
            {description = "1.33", data = 1.333, hover = "Every 1.33 days they need 1 fuel"},
            {description = "1.50", data = 1.500, hover = "Every 1.50 days they need 1 fuel"},
            {description = "1.66", data = 1.666, hover = "Every 1.66 days they need 1 fuel"},
            {description = "2", data = 2, hover = "Every 2 days they need 1 fuel"},
            {description = "2.33", data = 2.333, hover = "Every 2 days they need 1 fuel"},
            {description = "2.50", data = 2.500, hover = "Every 2 days they need 1 fuel"},
            {description = "2.66", data = 2.666, hover = "Every 2 days they need 1 fuel"},
            {description = "3", data = 3, hover = "Every 3 days they need 1 fuel"},
            {description = "3.33", data = 3.333, hover = "Every 3 days they need 1 fuel"},
            {description = "3.50", data = 3.500, hover = "Every 3 days they need 1 fuel"},
            {description = "3.66", data = 3.666, hover = "Every 3 days they need 1 fuel"},
            {description = "4", data = 4, hover = "Every 4 days they need 1 fuel"},
            {description = "4.33", data = 4.333, hover = "Every 4 days they need 1 fuel"},
            {description = "4.50", data = 4.500, hover = "Every 4 days they need 1 fuel"},
            {description = "4.66", data = 4.666, hover = "Every 4 days they need 1 fuel"},
            {description = "5", data = 5, hover = "Every 5 days they need 1 fuel"},
            {description = "Off", data = -1, hover = "No decay, shadows last as long as you want"}, -- in case a user is searchig in this direction for unlimited
        },
        default = 1,
	},
    {
        name = "durability_shadows_equipment",
        label = "Durability Equipment",
        hover = "Equipment given to shadows will deplete or last longer/forever? Only affects finiteuses (tools+weapons) and armor, not fueld or perishable items!",
        options =
        {
            {description = "Normal", data = false, hover = "Everything will break like normal"},
            {description = "Half duration", data = 0.5, hover = ""},
            {description = "Double duration", data = 2, hover = ""},
            {description = "Tripple duration", data = 3, hover = "Recommended to compensate early ineffectivness of workers"},
            {description = "Four times duration", data = 4, hover = ""},
            {description = "Five times duration", data = 5, hover = ""},
            {description = "Ten times duration", data = 10, hover = ""},
            {description = "Infinite", data = true, hover = "Weapons/tools and armor will never break"},
        },
        default = 3,
	},
    {
        name = "maxwell_shadow_hitstuntimeout",
        label = "HitStun Timeout",
        hover = "The seconds after another hitstun can happen when attacked. lvl 0 to lvl 100. Workers will have half values.",
        options =
        {
            {description = "0-0", data = "0-0", hover = "at lvl 0: 0 sec timeout, at lvl 100: 0 sec timeout"},
            {description = "0-1", data = "0-1", hover = "at lvl 0: 0 sec timeout, at lvl 100: 1 sec timeout"},
            {description = "0-2", data = "0-2", hover = "at lvl 0: 0 sec timeout, at lvl 100: 2 sec timeout"},
            {description = "0-3", data = "0-3", hover = "at lvl 0: 0 sec timeout, at lvl 100: 3 sec timeout"},
            {description = "0-4", data = "0-4", hover = "at lvl 0: 0 sec timeout, at lvl 100: 4 sec timeout"},
            {description = "0-5", data = "0-5", hover = "at lvl 0: 0 sec timeout, at lvl 100: 5 sec timeout - Recommended"},
            {description = "0-10", data = "0-10", hover = "at lvl 0: 0 sec timeout, at lvl 100: 10 sec timeout"},
            {description = "1-1", data = "1-1", hover = "at lvl 0: 1 sec timeout, at lvl 100: 1 sec timeout"},
            {description = "1-2", data = "1-2", hover = "at lvl 0: 1 sec timeout, at lvl 100: 2 sec timeout"},
            {description = "1-3", data = "1-3", hover = "at lvl 0: 1 sec timeout, at lvl 100: 3 sec timeout"},
            {description = "1-4", data = "1-4", hover = "at lvl 0: 1 sec timeout, at lvl 100: 4 sec timeout"},
            {description = "1-5", data = "1-5", hover = "at lvl 0: 1 sec timeout, at lvl 100: 5 sec timeout"},
            {description = "1-10", data = "1-10", hover = "at lvl 0: 1 sec timeout, at lvl 100: 10 sec timeout"},
            {description = "2-2", data = "2-2", hover = "at lvl 0: 2 sec timeout, at lvl 100: 2 sec timeout"},
            {description = "2-3", data = "2-3", hover = "at lvl 0: 2 sec timeout, at lvl 100: 3 sec timeout"},
            {description = "2-4", data = "2-4", hover = "at lvl 0: 2 sec timeout, at lvl 100: 4 sec timeout"},
            {description = "2-5", data = "2-5", hover = "at lvl 0: 2 sec timeout, at lvl 100: 5 sec timeout"},
            {description = "2-10", data = "2-10", hover = "at lvl 0: 2 sec timeout, at lvl 100: 10 sec timeout"},
            {description = "3-3", data = "3-3", hover = "at lvl 0: 3 sec timeout, at lvl 100: 3 sec timeout"},
            {description = "3-4", data = "3-4", hover = "at lvl 0: 3 sec timeout, at lvl 100: 4 sec timeout"},
            {description = "3-5", data = "3-5", hover = "at lvl 0: 3 sec timeout, at lvl 100: 5 sec timeout"},
            {description = "3-10", data = "3-10", hover = "at lvl 0: 3 sec timeout, at lvl 100: 10 sec timeout"},
            {description = "4-4", data = "4-4", hover = "at lvl 0: 4 sec timeout, at lvl 100: 4 sec timeout"},
            {description = "4-5", data = "4-5", hover = "at lvl 0: 4 sec timeout, at lvl 100: 5 sec timeout"},
            {description = "4-10", data = "4-10", hover = "at lvl 0: 4 sec timeout, at lvl 100: 10 sec timeout"},
            {description = "5-5", data = "5-5", hover = "at lvl 0: 5 sec timeout, at lvl 100: 5 sec timeout"},
            {description = "5-10", data = "5-10", hover = "at lvl 0: 5 sec timeout, at lvl 100: 10 sec timeout"},
            {description = "10-10", data = "10-10", hover = "at lvl 0: 10 sec timeout, at lvl 100: 10 sec timeout"},

        },
        default = "0-5",
	},
    {
        name = "null",
        label = "## Shadow Duelist settings ##",
        hover = "",
        options =	{
						{description = "", data = 1, hover = ""},
					},
        default = 1,
	},
    {
        name = "maxwell_shadow_health",
        label = "Duelist Health",
        hover = "Set Health of duelist at level 0 and maxlevel 100 (after 100 nightmarefuel given)",
        options =
        {
            {description = "100-100", data = "100-100", hover = "at lvl 0: 100 health, at lvl 100: 100 health"},
            {description = "100-250", data = "100-250", hover = "at lvl 0: 100 health, at lvl 100: 250 health"},
            {description = "100-500", data = "100-500", hover = "at lvl 0: 100 health, at lvl 100: 500 health"},
            {description = "100-1000", data = "100-1000", hover = "at lvl 0: 100 health, at lvl 100: 1000 health"},
            {description = "100-2500", data = "100-2500", hover = "at lvl 0: 100 health, at lvl 100: 2500 health - Recommended"},
            {description = "100-5000", data = "100-5000", hover = "at lvl 0: 100 health, at lvl 100: 5000 health"},
            {description = "100-10000", data = "100-10000", hover = "at lvl 0: 100 health, at lvl 100: 10000 health"},
            {description = "250-250", data = "250-250", hover = "at lvl 0: 250 health, at lvl 100: 250 health"},
            {description = "250-500", data = "250-500", hover = "at lvl 0: 250 health, at lvl 100: 500 health"},
            {description = "250-1000", data = "250-1000", hover = "at lvl 0: 250 health, at lvl 100: 1000 health"},
            {description = "250-2500", data = "250-2500", hover = "at lvl 0: 250 health, at lvl 100: 2500 health"},
            {description = "250-5000", data = "250-5000", hover = "at lvl 0: 250 health, at lvl 100: 5000 health"},
            {description = "250-10000", data = "250-10000", hover = "at lvl 0: 250 health, at lvl 100: 10000 health"},
            {description = "500-500", data = "500-500", hover = "at lvl 0: 500 health, at lvl 100: 500 health"},
            {description = "500-1000", data = "500-1000", hover = "at lvl 0: 500 health, at lvl 100: 1000 health"},
            {description = "500-2500", data = "500-2500", hover = "at lvl 0: 500 health, at lvl 100: 2500 health"},
            {description = "500-5000", data = "500-5000", hover = "at lvl 0: 500 health, at lvl 100: 5000 health"},
            {description = "500-10000", data = "500-10000", hover = "at lvl 0: 500 health, at lvl 100: 10000 health"},
            {description = "1000-1000", data = "1000-1000", hover = "at lvl 0: 1000 health, at lvl 100: 1000 health"},
            {description = "1000-2500", data = "1000-2500", hover = "at lvl 0: 1000 health, at lvl 100: 2500 health"},
            {description = "1000-5000", data = "1000-5000", hover = "at lvl 0: 1000 health, at lvl 100: 5000 health"},
            {description = "1000-10000", data = "1000-10000", hover = "at lvl 0: 1000 health, at lvl 100: 10000 health"},
            {description = "2500-2500", data = "2500-2500", hover = "at lvl 0: 2500 health, at lvl 100: 2500 health"},
            {description = "2500-5000", data = "2500-5000", hover = "at lvl 0: 2500 health, at lvl 100: 5000 health"},
            {description = "2500-10000", data = "2500-10000", hover = "at lvl 0: 2500 health, at lvl 100: 10000 health"},
            {description = "5000-5000", data = "5000-5000", hover = "at lvl 0: 5000 health, at lvl 100: 5000 health"},
            {description = "5000-10000", data = "5000-10000", hover = "at lvl 0: 5000 health, at lvl 100: 10000 health"},
            {description = "10000-10000", data = "10000-10000", hover = "at lvl 0: 10000 health, at lvl 100: 10000 health"},

        },
        default = "100-2500",
	},
    {
        name = "maxwell_shadow_healthregen",
        label = "Duelist Health-Regeneration",
        hover = "Regenerate x Health every 2 seconds. Doubles at maxlevel 100. You can give them armor!",
        options =
        {
            {description = "0", data = 0},
            {description = "1", data = 1},
            {description = "2", data = 2},
            {description = "3", data = 3},
            {description = "4", data = 4},
            {description = "5", data = 5},
            {description = "6", data = 6},
            {description = "7", data = 7},
            {description = "8", data = 8},
            {description = "9", data = 9},
            {description = "10", data = 10, hover = "Recommended"},
            {description = "Vanilla (15)", data = false, hover = "Vanilla Setting"},
            {description = "20", data = 20},
            {description = "30", data = 30},
            {description = "40", data = 40},
            {description = "50", data = 50},
            {description = "60", data = 60},
            {description = "70", data = 70},
            {description = "80", data = 80},
            {description = "90", data = 90},
            {description = "100", data = 100},
            {description = "200", data = 200},
            {description = "500", data = 500},
        },
        default = 10,
	},
    {
        name = "maxwell_shadow_damage",
        label = "Duelist Damage Multiplier",
        hover = "Set damagemultiplier of duelist at level 0 and maxlevel 100 (after 100 nightmarefuel). Damage depends on the weapon (20 without)",
        options =
        {
            {description = "0.75-0.75", data = "0.75-0.75", hover = "at lvl 0: *0.75 damage, at lvl 100: *0.75 damage"},
            {description = "0.75-1", data = "0.75-1", hover = "at lvl 0: *0.75 damage, at lvl 100: *1 damage"},
            {description = "0.75-2", data = "0.75-2", hover = "at lvl 0: *0.75 damage, at lvl 100: *2 damage"},
            {description = "0.75-3", data = "0.75-3", hover = "at lvl 0: *0.75 damage, at lvl 100: *3 damage"},
            {description = "0.75-4", data = "0.75-4", hover = "at lvl 0: *0.75 damage, at lvl 100: *4 damage"},
            {description = "0.75-5", data = "0.75-5", hover = "at lvl 0: *0.75 damage, at lvl 100: *5 damage"},
            {description = "0.75-10", data = "0.75-10", hover = "at lvl 0: *0.75 damage, at lvl 100: *10 damage"},
            {description = "1-1", data = "1-1", hover = "at lvl 0: *1 damage, at lvl 100: *1 damage"},
            {description = "1-2", data = "1-2", hover = "at lvl 0: *1 damage, at lvl 100: *2 damage"},
            {description = "1-3", data = "1-3", hover = "at lvl 0: *1 damage, at lvl 100: *3 damage"},
            {description = "1-4", data = "1-4", hover = "at lvl 0: *1 damage, at lvl 100: *4 damage"},
            {description = "1-5", data = "1-5", hover = "at lvl 0: *1 damage, at lvl 100: *5 damage - Recommended"},
            {description = "1-10", data = "1-10", hover = "at lvl 0: *1 damage, at lvl 100: *10 damage"},
            {description = "2-2", data = "2-2", hover = "at lvl 0: *2 damage, at lvl 100: *2 damage"},
            {description = "2-3", data = "2-3", hover = "at lvl 0: *2 damage, at lvl 100: *3 damage"},
            {description = "2-4", data = "2-4", hover = "at lvl 0: *2 damage, at lvl 100: *4 damage"},
            {description = "2-5", data = "2-5", hover = "at lvl 0: *2 damage, at lvl 100: *5 damage"},
            {description = "2-10", data = "2-10", hover = "at lvl 0: *2 damage, at lvl 100: *10 damage"},
            {description = "3-3", data = "3-3", hover = "at lvl 0: *3 damage, at lvl 100: *3 damage"},
            {description = "3-4", data = "3-4", hover = "at lvl 0: *3 damage, at lvl 100: *4 damage"},
            {description = "3-5", data = "3-5", hover = "at lvl 0: *3 damage, at lvl 100: *5 damage"},
            {description = "3-10", data = "3-10", hover = "at lvl 0: *3 damage, at lvl 100: *10 damage"},
            {description = "4-4", data = "4-4", hover = "at lvl 0: *4 damage, at lvl 100: *4 damage"},
            {description = "4-5", data = "4-5", hover = "at lvl 0: *4 damage, at lvl 100: *5 damage"},
            {description = "4-10", data = "4-10", hover = "at lvl 0: *4 damage, at lvl 100: *10 damage"},
            {description = "5-5", data = "5-5", hover = "at lvl 0: *5 damage, at lvl 100: *5 damage"},
            {description = "5-10", data = "5-10", hover = "at lvl 0: *5 damage, at lvl 100: *10 damage"},
            {description = "10-10", data = "10-10", hover = "at lvl 0: *10 damage, at lvl 100: *10 damage"},

        },
        default = "1-5",
	},
    {
        name = "maxwell_shadow_attackperiod",
        label = "Duelist Attack Speed",
        hover = "Attack every x seconds, if tanking. If kiting the attack speed is automatically adjusted to make kiting possible, depending on set kiting values.",
        options =
        {
            {description = "every 0.5 s", data = 0.5, hover = "Players Speed. Lower not possible because of animation speed"}, -- faster is not possible, because of animation
            {description = "every 0.75 s", data = 0.75},
            {description = "every 1 s", data = 1, hover = "Recommended"},
            {description = "every 1.5 s", data = 1.5},
            {description = "Vanilla (every 2 s)", data = false, hover = "Vanilla Setting"},
            {description = "every 2.5 s", data = 2.5},
            {description = "every 3 s", data = 3},
            {description = "every 4 s", data = 4},
            {description = "every 5 s", data = 5},
            {description = "every 10 s", data = 10},
        },
        default = 1,
	},   
    {
        name = "switch_option_fighter",
        label = "Duelist Tactics",
        hover = "Shadow Duelist will tank or kite creatures?",
        options =
        {
            {description = "Kite", data = "kite", hover = "Vanilla behaviour"},
            {description = "Smart kiting", data = "tactic", hover = "Kite as normal, unless they've been given armor"},
            {description = "Tank", data = "tank", hover = "Tank creatures without fear"},
        },
        default = "tactic",
	},
    {
        name = "stop_kiting_distance",
        label = "Duelist stop_kiting Distance",
        hover = "Set the range the duelist aims to be away from enemy, before attacking again. Attack period is automatically adjusted to achieve your setting.",
        options =
        {
            {description = "1", data = 1, hover = ""},
            {description = "2", data = 2, hover = ""},
            {description = "3", data = 3, hover = ""},
            {description = "4", data = 4, hover = ""},
            {description = "Vanilla (5)", data = 5, hover = "Vanilla Setting - Recommended"},
            {description = "6", data = 6, hover = ""},
            {description = "7", data = 7, hover = ""},
            {description = "8", data = 8, hover = ""},
            {description = "9", data = 9, hover = ""},
            {description = "10", data = 10, hover = ""},
        },
        default = 5,
	},
    {
        name = "shadow_attackshadow",
        label = "Duelists also attack shadowcreatures?",
        hover = "",
        options =
        {
            {description = "No", data = false, hover = ""},
            {description = "Yes", data = true, hover = ""},
        },
        default = false,
	},
    {
        name = "null",
        label = "##### Workers settings #####",
        hover = "",
        options =	{
						{description = "", data = 1, hover = ""},
					},
        default = 1,
	},
    {
        name = "maxwell_workers_health",
        label = "Worker Health",
        hover = "Health of workers at level 0 and maxlevel 20 (after 20 nightmarefuel). Most of the time they are not attacked/run away, but can still die by AoE Damage and such.",
        options =
        {
            {description = "1-1", data = "1-1", hover = "at lvl 0: 1 health, at lvl 20: 1 health"},
            {description = "1-100", data = "1-100", hover = "at lvl 0: 1 health, at lvl 20: 100 health"},
            {description = "1-250", data = "1-250", hover = "at lvl 0: 1 health, at lvl 20: 250 health - Recommended"},
            {description = "1-500", data = "1-500", hover = "at lvl 0: 1 health, at lvl 20: 500 health"},
            {description = "1-1000", data = "1-1000", hover = "at lvl 0: 1 health, at lvl 20: 1000 health"},
            {description = "1-5000", data = "1-5000", hover = "at lvl 0: 1 health, at lvl 20: 5000 health"},
            {description = "100-100", data = "100-100", hover = "at lvl 0: 100 health, at lvl 20: 100 health"},
            {description = "100-250", data = "100-250", hover = "at lvl 0: 100 health, at lvl 20: 250 health"},
            {description = "100-500", data = "100-500", hover = "at lvl 0: 100 health, at lvl 20: 500 health"},
            {description = "100-1000", data = "100-1000", hover = "at lvl 0: 100 health, at lvl 20: 1000 health"},
            {description = "100-5000", data = "100-5000", hover = "at lvl 0: 100 health, at lvl 20: 5000 health"},
            {description = "250-250", data = "250-250", hover = "at lvl 0: 250 health, at lvl 20: 250 health"},
            {description = "250-500", data = "250-500", hover = "at lvl 0: 250 health, at lvl 20: 500 health"},
            {description = "250-1000", data = "250-1000", hover = "at lvl 0: 250 health, at lvl 20: 1000 health"},
            {description = "250-5000", data = "250-5000", hover = "at lvl 0: 250 health, at lvl 20: 5000 health"},
            {description = "500-500", data = "500-500", hover = "at lvl 0: 500 health, at lvl 20: 500 health"},
            {description = "500-1000", data = "500-1000", hover = "at lvl 0: 500 health, at lvl 20: 1000 health"},
            {description = "500-5000", data = "500-5000", hover = "at lvl 0: 500 health, at lvl 20: 5000 health"},
            {description = "1000-1000", data = "1000-1000", hover = "at lvl 0: 1000 health, at lvl 20: 1000 health"},
            {description = "1000-5000", data = "1000-5000", hover = "at lvl 0: 1000 health, at lvl 20: 5000 health"},
            {description = "5000-5000", data = "5000-5000", hover = "at lvl 0: 5000 health, at lvl 20: 5000 health"},
        },
        default = "1-250",
	},
    {
        name = "maxwell_workers_health_regen",
        label = "Workers Health Regeneration",
        hover = "Regenerate x Health every 2 seconds. Doubles at maxlevel 20. Most of the time they are not attacked/run away, but can still die by AoE Damage and such.",
        options =
        {
            {description = "Vanilla (Off)", data = false, hover = "Vanilla Setting"},
            {description = "1", data = 1},
            {description = "2", data = 2, hover = "Recommended"},
            {description = "3", data = 3},
            {description = "4", data = 4},
            {description = "5", data = 5},
            {description = "6", data = 6},
            {description = "7", data = 7},
            {description = "8", data = 8},
            {description = "9", data = 9},
            {description = "10", data = 10},
            {description = "15", data = 15},
            {description = "20", data = 20},
            {description = "30", data = 30},
            {description = "40", data = 40},
            {description = "50", data = 50},
            {description = "60", data = 60},
            {description = "70", data = 70},
            {description = "80", data = 80},
            {description = "90", data = 90},
            {description = "100", data = 100},
            {description = "200", data = 200},
            {description = "500", data = 500},
        },
        default = 2,
	},
    {
        name = "upgrade_workingspeed",
        label = "Upgrade Working Speed?",
        hover = "Chop+Mining can get worse and better. Dig only worse and Pick only better than default player. Max level for worker is 20.",
        options =
        {
            {description = "Off", data = "1-1", hover = "Always same speed as default player"},
            {description = "*(1/3) to *3", data = "0.33333333-3", hover = "3 times slower on level 0 and 3 times faster on max level"},
            {description = "*1 to *3", data = "1-3", hover = "players speed at level 0 and 3 times faster on max level"},
            {description = "*(1/3) to *1", data = "0.33333333-1", hover = "3 times slower on level 0 and players speed on max level"},
            {description = "*(1/3) to *5", data = "0.33333333-5", hover = "3 times slower on level 0 and 5 times faster on max level"},
            {description = "*(1/5) to *5", data = "0.2-5", hover = "5 times slower on level 0 and 5 times faster on max level"},
            {description = "*1 to *5", data = "1-5", hover = "players speed at level 0 and 5 times faster on max level"},
            {description = "*(1/5) to *1", data = "0.2-1", hover = "5 times slower on level 0 and players speed on max level"},
            {description = "*(1/5) to *3", data = "0.2-3", hover = "5 times slower on level 0 and 3 times faster on max level"},
        },
        default = "0.33333333-3",
	},
	{
        name = "whendigup",
        label = "Dig Condition",
        hover = "When should Shadow digger dig saplings/grass/bushes? Ignores always withered/diseased/barren plants.",
        options =
        {
            {description = "Never", data = "never", hover = "Vanilla Setting"},
            {description = "Shovel equipped", data = "shovel", hover = "When maxwell has a shovel equipped"},
            {description = "Always", data = "always", hover = ""},
        },
        default = "shovel",
	},
    {
        name = "shadow_preferable_tree",
        label = "Lumber's Tree-Stage",
        hover = "Set on which stage to chop trees (just planted trees are always ignored)",
        options =
        {
            {description = "All", data = false, hover = "Vanilla Setting"},
            {description = "Small", data = "small", hover = "Only Small Trees"},
			{description = "Normal", data = "normal", hover = "Only Medium Trees"},
            {description = "Tall", data = "tall", hover = "Only Fully Grown Trees"},
        },
        default = "tall",
	},
    {
        name = "shadow_savethetrees",
        label = "Lumber's spare trees without seeds?",
        hover = "Spare Mushtree, Lumpy Evergreen, Spikey or Banana Tree or Barren Birchnut Tree?",
        options =
        {
            {description = "No", data = false, hover = "All of those trees will be chopped"},
            {description = "Yes", data = true, hover = "None of these trees wil be chopped by shadows"},
        },
        default = true,
	},
	{
        name = "working_distance",
        label = "Keep working/attacking Range",
        hover = "Set range value for shadows to maxwell to keep them working/attacking (eg. while you move away). Should always be higher than sight!",
        options =
        {
            {description = "6", data = 6, hover = ""},
            {description = "8", data = 8, hover = ""},
            {description = "10", data = 10, hover = ""},
            {description = "12", data = 12, hover = ""},
			{description = "Vanilla (14)", data = 14, hover = "Vanilla Setting"},
		    {description = "16", data = 16, hover = "Recommended"},
		    {description = "18", data = 18, hover = ""},
		    {description = "20", data = 20, hover = ""},
            {description = "22", data = 22, hover = ""},
            {description = "24", data = 24, hover = ""},
            {description = "26", data = 26, hover = ""},
            {description = "28", data = 28, hover = ""},
            {description = "30", data = 30, hover = ""},
        },
        default = 16,
	},
	{
        name = "see_working_distance",
        label = "Workers Sight",
        hover = "Set the range of sight from maxwell to help them find materials and start working. Should be lower than working range!",
        options =
        {
		    {description = "6", data = 6, hover = ""},
            {description = "8", data = 8, hover = ""},
            {description = "Vanilla (10)", data = 10, hover = "Vanilla Setting"},
            {description = "12", data = 12, hover = "Recommended"},
			{description = "14", data = 14, hover = ""},
		    {description = "16", data = 16, hover = ""},
		    {description = "18", data = 18, hover = ""},
		    {description = "20", data = 20, hover = ""},
            {description = "22", data = 22, hover = ""},
            {description = "24", data = 24, hover = ""},
            {description = "26", data = 26, hover = ""},
            {description = "28", data = 28, hover = ""},
            {description = "30", data = 30, hover = ""},
        },
        default = 12,
	},
    {
		name = "examine",
		label = "Examine Info",
		hover = "See info about level, decay, health, damage and workmultiplier on examine?",
		options =	{
						{description = "No", data = false, hover = "\n"},
                        {description = "Yes", data = true, hover = "Default"},
					},
		default = true,
	},
}
